/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tiand
 */
public class fomenu extends javax.swing.JFrame {

    /**
     * Creates new form vonat
     */
    public fomenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nev = new javax.swing.JLabel();
        ticketBuy_btn = new javax.swing.JButton();
        favorites_btn = new javax.swing.JButton();
        userInfo_btn = new javax.swing.JButton();
        history_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_nev.setText("Név");

        ticketBuy_btn.setText("Jegy vásárlás");
        ticketBuy_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketBuy_btnActionPerformed(evt);
            }
        });

        favorites_btn.setText("Kedvencek");

        userInfo_btn.setText("Saját adatok");
        userInfo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInfo_btnActionPerformed(evt);
            }
        });

        history_btn.setText("Megvásárolt jegyek");
        history_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                history_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userInfo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(ticketBuy_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(favorites_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(history_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lbl_nev, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_nev)
                .addGap(57, 57, 57)
                .addComponent(ticketBuy_btn)
                .addGap(18, 18, 18)
                .addComponent(userInfo_btn)
                .addGap(18, 18, 18)
                .addComponent(favorites_btn)
                .addGap(18, 18, 18)
                .addComponent(history_btn)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setFieldText(String text) {
        lbl_nev.setText(text);
    }
    //A gombok megnyomására eldobja a főmenü oldalt és megnyitja a gombhoz járuló JFrame-t
    private void ticketBuy_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketBuy_btnActionPerformed
        // TODO add your handling code here:
        super.dispose();
        jegyvasarlas vasarlas = new jegyvasarlas();
        vasarlas.setVisible(true);
    }//GEN-LAST:event_ticketBuy_btnActionPerformed

    
    private void history_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_history_btnActionPerformed
        // TODO add your handling code here:
        super.dispose();
        kedvencek kedvenc = new kedvencek();
        kedvenc.setVisible(true);
    }//GEN-LAST:event_history_btnActionPerformed

    private void userInfo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInfo_btnActionPerformed
        // TODO add your handling code here:
        super.dispose();
        SajatAdatok userInfo = new SajatAdatok();
        userInfo.setVisible(true);
    }//GEN-LAST:event_userInfo_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fomenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton favorites_btn;
    private javax.swing.JButton history_btn;
    private javax.swing.JLabel lbl_nev;
    private javax.swing.JButton ticketBuy_btn;
    private javax.swing.JButton userInfo_btn;
    // End of variables declaration//GEN-END:variables
}
